export const AI_CONNECTION_PRESETS = [
    {
        id: 'openai',
        label: 'OpenAI',
        connectionName: 'OpenAI',
        driver: 'openai',
        baseUrl: 'https://api.openai.com/v1',
        defaultModel: 'gpt-5.2',
        models: ['gpt-5.2', 'gpt-5-mini', 'gpt-5-nano'],
        docsUrl: 'https://platform.openai.com/docs/models',
        note: 'Direct OpenAI API access for GPT models.',
    },
    {
        id: 'anthropic',
        label: 'Anthropic Claude',
        connectionName: 'Anthropic Claude',
        driver: 'anthropic',
        baseUrl: 'https://api.anthropic.com/v1',
        defaultModel: 'claude-sonnet-4-0',
        models: ['claude-opus-4-1', 'claude-sonnet-4-0', 'claude-3-5-haiku-latest'],
        docsUrl: 'https://docs.anthropic.com/en/docs/about-claude/models/all-models',
        note: 'Native Claude connection with Anthropic headers and model discovery.',
    },
    {
        id: 'gemini',
        label: 'Google Gemini',
        connectionName: 'Google Gemini',
        driver: 'openai',
        baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
        defaultModel: 'gemini-2.5-flash',
        models: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-2.5-flash-lite'],
        docsUrl: 'https://ai.google.dev/gemini-api/docs/openai',
        note: 'Uses the Gemini OpenAI-compatible endpoint.',
    },
    {
        id: 'xai',
        label: 'xAI Grok',
        connectionName: 'xAI Grok',
        driver: 'openai',
        baseUrl: 'https://api.x.ai/v1',
        defaultModel: 'grok-4',
        models: ['grok-4', 'grok-4-1-fast-reasoning', 'grok-code-fast-1'],
        docsUrl: 'https://docs.x.ai/developers/models',
        note: 'Grok models through the xAI API.',
    },
    {
        id: 'groq',
        label: 'Groq',
        connectionName: 'Groq',
        driver: 'openai',
        baseUrl: 'https://api.groq.com/openai/v1',
        defaultModel: 'openai/gpt-oss-120b',
        models: ['openai/gpt-oss-120b', 'groq/compound-mini', 'llama-3.3-70b-versatile'],
        docsUrl: 'https://console.groq.com/docs/models',
        note: 'Low-latency OpenAI-compatible inference on Groq hardware.',
    },
    {
        id: 'deepseek',
        label: 'DeepSeek',
        connectionName: 'DeepSeek',
        driver: 'openai',
        baseUrl: 'https://api.deepseek.com/v1',
        defaultModel: 'deepseek-chat',
        models: ['deepseek-chat', 'deepseek-reasoner'],
        docsUrl: 'https://api-docs.deepseek.com/',
        note: 'OpenAI-compatible DeepSeek endpoint.',
    },
    {
        id: 'mistral',
        label: 'Mistral',
        connectionName: 'Mistral',
        driver: 'openai',
        baseUrl: 'https://api.mistral.ai/v1',
        defaultModel: 'mistral-large-latest',
        models: ['mistral-large-latest', 'mistral-small-latest', 'codestral-latest'],
        docsUrl: 'https://docs.mistral.ai/getting-started/changelog/',
        note: 'Mistral API with chat completions and model listing.',
    },
    {
        id: 'openrouter',
        label: 'OpenRouter',
        connectionName: 'OpenRouter',
        driver: 'openai',
        baseUrl: 'https://openrouter.ai/api/v1',
        defaultModel: 'openrouter/auto',
        models: ['openrouter/auto', 'openai/gpt-5.2', 'anthropic/claude-sonnet-4.5', 'google/gemini-3-pro-preview'],
        docsUrl: 'https://openrouter.ai/docs/features/model-routing',
        note: 'One connection that can route requests across multiple model families.',
    },
    {
        id: 'perplexity',
        label: 'Perplexity Sonar',
        connectionName: 'Perplexity Sonar',
        driver: 'openai',
        baseUrl: 'https://api.perplexity.ai',
        defaultModel: 'sonar-pro',
        models: ['sonar', 'sonar-pro', 'sonar-reasoning-pro', 'sonar-deep-research'],
        docsUrl: 'https://docs.perplexity.ai/models/model-cards',
        note: 'Perplexity Sonar models via an OpenAI-style chat completions API.',
    },
];

export const DEFAULT_AI_CONNECTION_PRESET_ID = 'openai';

export function findAiConnectionPresetById(id) {
    return AI_CONNECTION_PRESETS.find((preset) => preset.id === id) ?? null;
}
